@startuml Catalogue update triggered schedule updates
title Catalogue update triggered schedule updates

start
  :De-duplicate schedules passed to function;
  repeat
    :Fetch schedule from store;
    :Filter out broadcasts not referencing episode pids passed to function;
    if (Has broadcasts to transform after filter) then (no)
      :Continue to next schedule;
    else (yes)
      :Transform new broadcasts linked to episodes;
      :Re-insert effected updated broadcasts into schedule;
    endif
  repeat while (Schedules left to process) is (yes) not (no);

  :Write successful schedule updates to redis in transcation;
  if (Schedule update errors occured) then (yes)
    :Send notification to re-process entire schedule;
    end
  else (no)
    end
  endif

@enduml